name: packaging

on:
  push:
    branch-ignore:
      - '*'
    tags:
      - 'v?\d+.\d+.\d+'
      - 'dev*'
      - 'pack*'

jobs:

  # ----- #
  # macOS #
  # ----- #
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      name: Checkout TTK-ParaView source code

    - name: Remove hosted Python
      run: |
        sudo rm -rf /usr/local/Frameworks/Python.framework

    - name: Install macOS dependencies
      run: |
        # ParaView dependencies
        brew install --cask xquartz
        brew install wget libomp mesa glew qt@5 ninja python@3.12

    - name: Create & configure ParaView build directory
      run: |
        mkdir build && cd build
        cmake \
          -DCMAKE_BUILD_TYPE=Release \
          -DQt5_DIR=$(brew --prefix qt@5)/lib/cmake/Qt5 \
          -DPython3_ROOT_DIR=$(brew --prefix python) \
          -GNinja \
          $GITHUB_WORKSPACE

    - name: Build ParaView
      run: |
        cd build
        cmake --build . --parallel

    - name: Create ParaView package
      run: |
        cd build
        cpack -G TGZ

    - name: Upload compressed binaries
      uses: actions/upload-artifact@v3
      with:
        name: ttk-paraview-macOS
        path: build/ttk-paraview.tar.gz


  # --------------------- #
  # Upload release assets #
  # --------------------- #
  create-release:
    runs-on: ubuntu-latest
    needs: [build-macos]
    steps:

    - name: Delete previous release
      uses: actions/github-script@v6
      continue-on-error: true
      with:
        script: |
          const { owner, repo } = context.repo
          const { data: { id } } = await github.rest.repos.getReleaseByTag({
            owner,
            repo,
            tag: "${{ github.ref_name }}"
          })
          await github.rest.repos.deleteRelease({ owner, repo, release_id: id })

    - name: Create Release
      uses: actions/github-script@v6
      with:
        script: |
          const { owner, repo } = context.repo
          await github.rest.repos.createRelease({
            owner,
            repo,
            tag_name: "${{ github.ref_name }}",
            name: "Release ${{ github.ref_name }}",
            draft: false,
            prerelease: false
          })

    - name: Fetch all uploaded artifacts
      uses: actions/download-artifact@v3

    - name: Upload .tar.gz as Release Asset
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: ttk-paraview-macOS/ttk-paraview.tar.gz
        asset_name: ttk-paraview-$tag.tar.gz

    - name: Delete package artifacts
      uses: geekyeggo/delete-artifact@v2
      with:
          name: |
              ttk-paraview*
